# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_auto_20160711_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankOfHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('start_time', models.TimeField(help_text='*', verbose_name='Hora de Entrada')),
                ('end_time', models.TimeField(help_text='*', verbose_name='Hora de Saída')),
                ('cumulative_hours', models.CharField(help_text='*', max_length=100, verbose_name='Horas')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observação')),
                ('work_date', models.DateTimeField(help_text='*', verbose_name='Data')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_of_hours', to='employee.Employee', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name_plural': 'Banco de Horas',
                'ordering': ['-id'],
                'verbose_name': 'Banco de Hora',
            },
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('amount_of_hours', models.CharField(help_text='*', max_length=100, verbose_name='Horas Compensadas')),
                ('compensated_date', models.DateTimeField(help_text='*', verbose_name='Data')),
                ('bank_of_hours', models.ManyToManyField(related_name='compensations', to='bank_of_hours.BankOfHours', verbose_name='Banco de Horas')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='employee.Employee', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name_plural': 'Compensações',
                'ordering': ['-id'],
                'verbose_name': 'Compensação',
            },
        ),
    ]
