# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_of_hours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensation',
            name='bank_of_hours',
        ),
    ]
