# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_of_hours', '0002_remove_compensation_bank_of_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankofhours',
            name='cumulative_hours',
            field=models.IntegerField(verbose_name='Horas Acumuladas'),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='amount_of_hours',
            field=models.IntegerField(verbose_name='Horas Compensadas'),
        ),
    ]
