# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_of_hours', '0003_auto_20160713_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankofhours',
            name='cumulative_hours',
            field=models.IntegerField(verbose_name='Horas acumuladas'),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='amount_of_hours',
            field=models.IntegerField(verbose_name='Horas a compensar'),
        ),
    ]
