# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_of_hours', '0004_auto_20160713_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankofhours',
            name='cumulative_hours',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Horas acumuladas'),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='amount_of_hours',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Horas a compensar'),
        ),
    ]
