# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('name', models.CharField(help_text='Este campo é obrigatório', max_length=100, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Função',
                'ordering': ['name'],
                'verbose_name_plural': 'Funções',
            },
        ),
    ]
