# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankOfHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('start_time', models.TimeField(help_text='*', verbose_name='Hora de Entrada')),
                ('end_time', models.TimeField(help_text='*', verbose_name='Hora de Saída')),
                ('cumulative_hours', models.CharField(help_text='*', max_length=100, verbose_name='Horas')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observação')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('amount_of_hours', models.CharField(help_text='*', max_length=100, verbose_name='Horas Compensadas')),
                ('bank_of_hours', models.ManyToManyField(related_name='compensations', to='employee.BankOfHours', verbose_name='Banco de Horas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='work_regime',
            field=models.IntegerField(default=None, help_text='*', verbose_name='Regime de Trabalho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='*', max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=models.CharField(help_text='*', max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='siape',
            field=models.IntegerField(help_text='*', unique=True, verbose_name='Siape'),
        ),
        migrations.AlterField(
            model_name='function',
            name='name',
            field=models.CharField(help_text='*', max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='compensation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='employee.Employee', verbose_name='Funcionário'),
        ),
        migrations.AddField(
            model_name='bankofhours',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_of_hours', to='employee.Employee', verbose_name='Funcionário'),
        ),
    ]
