# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20160708_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankofhours',
            options={'ordering': ['-id'], 'verbose_name': 'Banco de Hora', 'verbose_name_plural': 'Banco de Horas'},
        ),
        migrations.AlterModelOptions(
            name='compensation',
            options={'ordering': ['-id'], 'verbose_name': 'Compensação', 'verbose_name_plural': 'Compensações'},
        ),
        migrations.AddField(
            model_name='bankofhours',
            name='work_date',
            field=models.DateTimeField(default=None, help_text='*', verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compensation',
            name='compestated_date',
            field=models.DateTimeField(default=None, help_text='*', verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_regime',
            field=models.IntegerField(blank=True, help_text='*', null=True, verbose_name='Regime de Trabalho'),
        ),
    ]
