# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20160708_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compensation',
            old_name='compestated_date',
            new_name='compensated_date',
        ),
    ]
