# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20160708_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankofhours',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='bank_of_hours',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='employee',
        ),
        migrations.DeleteModel(
            name='BankOfHours',
        ),
        migrations.DeleteModel(
            name='Compensation',
        ),
    ]
