# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20160713_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_regime',
            field=models.IntegerField(blank=True, choices=[(40, '40 - Horas Semanais'), (30, '30 - Horas Semanais'), (20, '20 - Horas Semanais')], default=40, help_text='*', null=True, verbose_name='Regime de Trabalho'),
        ),
    ]
